name: esip-tech-dive
channels:
  - conda-forge
dependencies:
  - conda=4.6
  - nomkl
  - s3fs=0.2
  - gcsfs=0.2
  - intake=0.5
  - intake-xarray=0.3
  - python=3.6
  - xarray=0.12
  - zarr=2.3
  - h5py=2.9
  - h5netcdf=0.7
  - dask=1.2
  - distributed=1.28
  - dask-kubernetes=0.8
  - matplotlib=3.1
  - nbserverproxy=0.8
  - jupyter=1.0
  - ipywidgets=7.4
  - graphviz=2.38
  - jupyterlab=0.35
  - libgdal=2.4
  - boto3=1.9
  - hvplot=0.4
  - geoviews-core=1.6
  - ipyleaflet=0.10
  - datashader=0.7
  - requests=2.22
  - pandas=0.24
  - geopandas=0.5
  - rasterio=1.0
  - pip:
    - sat-search==0.2
    - dask-labextension==0.3
