name: esip-tech-dive
channels:
  - conda-forge
dependencies:
  - python=3.6
  - libgdal=2.4
#  - tornado=5.1.1
  - nomkl
  - s3fs
  - gcsfs
  - intake
  - intake-xarray
  - python
  - xarray
  - zarr
  - h5py
  - h5netcdf
  - matplotlib
  - boto3
  - hvplot
  - geoviews-core
  - ipyleaflet
  - datashader
  - requests
  - pandas
  - geopandas
  - rasterio
  - pip
  - pip:
    - sat-search
